# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('gp', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('jersey_number', models.IntegerField(default=-1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
    ]
